name: Call reusable workflow

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      input1: value1
      input2: value2
    secrets: inherit
