name: Create Release Workflow

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate release tag
        id: generate_release_tag
        run: |
          echo "TAG_NAME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create Release
        run: |
          echo "Creating release..."
          gh release create ${{ steps.generate_release_tag.outputs.TAG_NAME }} --title "Release ${{ steps.generate_release_tag.outputs.TAG_NAME }}" --generate-notes --target main 
