name: publish event dispatcher

on:
  release:
    types: [published]

jobs:
  event_dispathch:
    runs-on: ubuntu-latest
    steps:
      - name: publish event
        env:
          REPOSITORY: 'y16ra/github-actions-receive-dispatch'
        run: |
          curl -X POST https://api.github.com/repos/${{ env.REPOSITORY }}/dispatches \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" \
            --data '{"event_type": "publish", "client_payload": { "event_type":"point_core_release", "version": "${{ github.event.release.tag_name }}" }}'
