name: Reusable workflow

on:
  workflow_call:
    inputs:
      input1:
        type: string
        description: 'Input 1'
        required: true
        default: 'default value'
      input2:
        type: string
        description: 'Input 2'
        required: true
        default: 'default value'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "Step 1"
          echo "Input 1: ${{ inputs.input1 }}"
      - name: Step 2
        run: |
          echo "Step 2"
          echo "Input 2: ${{ inputs.input2 }}"
      - name: Step 3
        run: echo "Step 3"
