name: Test workfow

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    env:
      TAG: refs/tags/v1.0.0
    steps:
      - name: Extract version from tag reference
        run: echo "VERSION=$(echo ${{ env.TAG#refs/tags/ }})" >> $GITHUB_ENV
      - name: Print version
        run: echo $VERSION

