name: Test workfow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of tag'
        required: true

env:
  RELEASE_VERSION: ${{ github.event.client_payload.version }}

jobs:
  test-job:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.inputs.name }}
      VERSION: 0.0.1
    steps:
      - name: Extract version from tag reference
        run:
          echo "VERSION=${TAG#refs/*/}" >> $GITHUB_ENV
      - name: Print version
        run: echo ${TAG#refs/*/}
      - name: Print release version
        run: echo $RELEASE_VERSION
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: test-repo
      - name: get commit id
        working-directory: ./test-repo
        run: |
          echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Print commit id
        run: |
          echo ${{ env.COMMIT_ID }}
          echo $COMMIT_ID
